### ISSUE TITLE
Units of imu sensor errors

### ISSUE THREAD

**Issue by swapnilsayansaha** [nmayorov/allan-variance#4]
If I feed accelerometer data in m/s^2 unit and dt in seconds, what is the unit of flicker and walk?

Same question for gyroscope data with unit in deg/s.

**Comment by nmayorov** [comment]
Sorry I've missed your question. This is indeed a somewhat tricky to figure out. 

The easiest way is to consider AVAR dependency. An effect with parameter `p` has theoretical dependency `AVAR ~ p**2 / tau**k`, where `k` varies from 2 to -2 for the parameters `'quantization', 'white', 'flicker', 'walk', 'ramp'` respectively. And AVAR values for a unit `U` has units `U**2`.

Then for units of `p` we have `P = U * tau**(0.5 * k)`. 

For accelerometers in m/s/s: `m/s, m/s**1.5, m/s**2, m/s**2.5, m/s**3`.
For gyros in deg/s: `deg, deg/s**0.5, deg/s, deg/s**1.5, deg/s**2`.

I will add a note into the docstring.
